"""Integration test for render_cache against real Neon."""

from __future__ import annotations

import pytest_asyncio

from app.db import get_conn
from app.services.render_cache import (
    cache_key,
    get_cached,
    record_hit,
    store,
)

# Sentinel keys that integration tests own. Real cache_keys are 64-char sha256
# hex; this prefix can't collide with one.
TEST_PREFIX = "test_"


async def _delete_test_keys() -> None:
    async with get_conn() as conn:
        await conn.execute(
            "DELETE FROM render_cache WHERE cache_key LIKE %s", (TEST_PREFIX + "%",)
        )


@pytest_asyncio.fixture
async def clean_cache():
    await _delete_test_keys()
    try:
        yield
    finally:
        await _delete_test_keys()


async def test_cache_miss_returns_none(clean_cache) -> None:
    assert await get_cached(TEST_PREFIX + "missing") is None


async def test_store_then_get_roundtrips(clean_cache) -> None:
    key = TEST_PREFIX + "rt1"
    await store(
        key,
        video_id="vid-rt1",
        download_url="https://example.com/a.mp4",
        local_path="/tmp/a.mp4",
    )
    cached = await get_cached(key)
    assert cached is not None
    assert cached["video_id"] == "vid-rt1"
    assert cached["download_url"] == "https://example.com/a.mp4"
    assert cached["local_path"] == "/tmp/a.mp4"


async def test_store_overwrites_on_conflict(clean_cache) -> None:
    key = TEST_PREFIX + "rt2"
    await store(key, video_id="vid-old", download_url=None, local_path="/tmp/old.mp4")
    await store(key, video_id="vid-new", download_url=None, local_path="/tmp/new.mp4")
    cached = await get_cached(key)
    assert cached is not None
    assert cached["video_id"] == "vid-new"
    assert cached["local_path"] == "/tmp/new.mp4"


async def test_record_hit_increments_count(clean_cache) -> None:
    key = TEST_PREFIX + "rt3"
    await store(key, video_id="v", download_url=None, local_path="/tmp/x.mp4")
    await record_hit(key)
    await record_hit(key)
    async with get_conn() as conn:
        cur = await conn.execute(
            "SELECT hit_count FROM render_cache WHERE cache_key = %s", (key,)
        )
        row = await cur.fetchone()
    assert row is not None
    assert row[0] == 2


async def test_cache_key_used_by_real_path() -> None:
    """End-to-end: a key generated by cache_key() can be stored & retrieved."""
    real_key = cache_key("test prompt", None, "16:9", 5.0, 30, "1080p")
    # No prefix — real key. Manually clean it after.
    try:
        async with get_conn() as conn:
            await conn.execute(
                "DELETE FROM render_cache WHERE cache_key = %s", (real_key,)
            )
        await store(real_key, video_id="vrk", download_url=None, local_path="/tmp/r.mp4")
        cached = await get_cached(real_key)
        assert cached is not None
        assert cached["video_id"] == "vrk"
    finally:
        async with get_conn() as conn:
            await conn.execute(
                "DELETE FROM render_cache WHERE cache_key = %s", (real_key,)
            )
